apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: <dsc_name>
  labels:
      app.kubernetes.io/created-by: <operator_yaml_label>
      app.kubernetes.io/instance: <dsc_name>
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: datasciencecluster
      app.kubernetes.io/part-of: <operator_yaml_label>
spec:
  components:
    dashboard:
      managementState: <dashboard_value>
    aipipelines:
      managementState: <aipipelines_value>
    kserve:
      managementState: <kserve_value>
      modelsAsService:
        managementState: <modelsasservice_value>
    kueue:
      managementState: <kueue_value>
    ray:
      managementState: <ray_value>
    trainingoperator:
      managementState: <trainingoperator_value>
    trainer:
      managementState: <trainer_value>
    trustyai:
      managementState: <trustyai_value>
    workbenches:
      managementState: <workbenches_value>
      workbenchNamespace: <workbenches_namespace>
    modelregistry:
      managementState: <modelregistry_value>
      registriesNamespace: <modelregistry_namespace>
    feastoperator:
      managementState: <feastoperator_value>
    llamastackoperator:
      managementState: <llamastackoperator_value>
    mlflowoperator:
      managementState: <mlflowoperator_value>
    sparkoperator:
      managementState: <sparkoperator_value>
