apiVersion: kueue.openshift.io/v1alpha1
kind: Kueue
metadata:
    name: <kueue_name>
    namespace: <kueue_namespace>
spec:
    config:
        integrations:
            frameworks:
                - RayCluster
                - Deployment
                - Pod
                - StatefulSet
                - TrainJob



