apiVersion: v1
kind: List
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterPool
  metadata:
    name: {{ hive_cluster_name|default("rhodsaws") }}-pool
    namespace: rhods
  spec:
    baseDomain: {{ base_domain }}
    imageSetRef:
      name: {{ image_set|default("rhods-openshift") }}
    platform:
      aws:
        region: {{ aws_region|default("us-east-1") }}
        credentialsSecretRef:
          name: aws-creds
    installConfigSecretTemplateRef:
      name: aws-sno-install-config
    size: 0
    skipMachinePools: true
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws-sno-install-config
    namespace: rhods
  type: Opaque
  stringData:
    install-config.yaml: |
      apiVersion: v1
      baseDomain: {{ base_domain }}
      compute:
      - name: worker
        platform:
          aws:
            type: {{ worker_node_instance_type|default("m5.2xlarge") }}
        replicas: {{ worker_node_replicas|default("2") }}
      controlPlane:
        name: master
        platform:
          aws:
            type: {{ master_node_instance_type|default("m5.2xlarge") }}
        replicas: {{ master_node_replicas|default("3") }}
      metadata:
        name: aws-sno
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: 10.0.0.0/16
        networkType: {{ ocp_network_type|default("OVNKubernetes") }}
        serviceNetwork:
        - 172.30.0.0/16
      fips: {{ fips_validation|default("false") }}
      platform:
        aws:
          region: {{ aws_region|default("us-east-1") }}
      pullSecret: {{ pull_secret|default("") }}
      sshKey: {{ ssh_key|default("") }}
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws-creds
    namespace: rhods
  type: Opaque
  stringData:
    aws_access_key_id: {{ AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: {{ AWS_SECRET_ACCESS_KEY }}
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    name: {{ image_set|default("rhods-openshift") }}
    namespace: rhods
  spec:
    releaseImage: {{ openshift_image|default("quay.io/openshift-release-dev/ocp-release:4.10.42-x86_64") }}
