apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterPool
  metadata:
    name: {{ hive_cluster_name|default("rhodsaws") }}
    namespace: rhods
  spec:
    baseDomain: rhods.ccitredhat.com
    imageSetRef:
      name: rhods-openshift
    platform:
      aws:
        region: {{ aws_region|default("us-east-1") }}
        credentialsSecretRef:
          name: aws-creds
    installConfigSecretTemplateRef:
      name: aws-sno-install-config
    size: 1
    skipMachinePools: true
- apiVersion: v1
  kind: Secret
  stringData:
    install-config.yaml: |
      apiVersion: v1
      baseDomain: rhods.ccitredhat.com
      compute:
      - name: worker
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 160
              type: gp2
            type: {{ worker_node_instance_type|default("m5.2xlarge") }}
        replicas: {{ worker_node_replicas|default("2") }}
      controlPlane:
        name: master
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 160
              type: gp2
            type: {{ master_node_instance_type|default("m5.2xlarge") }}
        replicas: {{ master_node_replicas|default("2") }}
      metadata:
        creationTimestamp: null
        name: aws-sno
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: 10.0.0.0/16
        networkType: OpenShiftSDN
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        aws:
          region: {{ aws_region|default("us-east-1") }}
      pullSecret: ""
      sshKey: {{ ssh_key|default(" ") }}
  metadata:
    name: aws-sno-install-config
    namespace: rhods
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws-creds
    namespace: rhods
  stringData:
    aws_access_key_id: {{ AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: {{ AWS_SECRET_ACCESS_KEY }}
  type: Opaque
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    name: rhods-openshift
    namespace: rhods
  spec:
    releaseImage: {{ openshift_image|default("quay.io/openshift-release-dev/ocp-release:4.10.18-x86_64") }}
kind: List
metadata: {}
