name: dryrun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dryrun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Execute ods-ci dryrun
        run: |
          mv test-variables.yml.example test-variables.yml
          ./run_robot_test.sh --extra-robot-args '--dryrun' --skip-oclogin true --no-output-subfolder true

      # Runs a set of commands using the runners shell
      - name: Parse output
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: test-output
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: false
